# 服务端口号
server:
  port: 8004
#server: 随机端口号
#  port: ${random.int[1000,19999]}



# 数据库地址
datasource:
  url: 192.168.18.8:3306/microservice04


spring:
  application:
    name: microservice-order # 对外暴露的服务名称

  datasource: # 数据库配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${datasource.url}?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 10 # 最大连接池数
      max-lifetime: 1770000

mybatis:
  # 指定别名设置的包为所有entity
  type-aliases-package: com.itcodai.springcloud.entity
  mapper-locations: # mapper映射文件位置
    - classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名规范

# 客户端注册进eureka服务列表里
eureka:
  client:
    service-url:
      defaultZone: http://mazhenqing:mazhenqing123456@eureka01:7001/hello/eureka/,http://mazhenqing:mazhenqing123456@eureka02:7002/hello/eureka/,http://mazhenqing:mazhenqing123456@eureka03:7003/hello/eureka/
    healthcheck:
      enabled: true
  instance:
    metadata-map:
      zone: shanghai #给对应的服务增加所在区域 因为ribbon 策略中有根据区域来 负载均衡的措施 而且ribbon默认的是区域亲和策略
    instance-id: 猫咪订单服务-8001  # 人性化显示出服务的信息
    prefer-ip-address: true    # 访问路径可显示ip地址 否则就以主机名注册
    lease-renewal-interval-in-seconds: 20 #参数用于定义服务续约任务的调用间隔时间,默认为30秒
    lease-expiration-duration-in-seconds: 50 #参数用于定义服务时效的时间,默认为90秒

# 使用actuator来展示项目的基本信息
info:
  author.name: zhenqing ma
  app.name: microservice
  server.port: ${server.port}
  application.name: ${spring.application.name}

# 配置hystrix dashboard的url访问
# 开启指标流端点
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

init-db: true



